sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '10.4.1'
cache:
  directories:
    "node_modules"
env:
    - BABEL_ENV=production
install:
- npm install
- npm run test:driverInstall
script:
- npm test
